/*
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.LocalDate;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * AstronautDetailedSerializerNoFlights
 */

public class AstronautDetailedSerializerNoFlights {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private AstronautType type = null;

  @SerializedName("status")
  private AstronautStatus status = null;

  @SerializedName("agency")
  private AgencySerializerMini agency = null;

  @SerializedName("date_of_birth")
  private LocalDate dateOfBirth = null;

  @SerializedName("date_of_death")
  private LocalDate dateOfDeath = null;

  @SerializedName("nationality")
  private String nationality = null;

  @SerializedName("twitter")
  private String twitter = null;

  @SerializedName("instagram")
  private String instagram = null;

  @SerializedName("bio")
  private String bio = null;

  @SerializedName("profile_image")
  private String profileImage = null;

  @SerializedName("wiki")
  private String wiki = null;

  @SerializedName("last_flight")
  private String lastFlight = null;

  @SerializedName("first_flight")
  private String firstFlight = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public AstronautDetailedSerializerNoFlights name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AstronautDetailedSerializerNoFlights type(AstronautType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public AstronautType getType() {
    return type;
  }

  public void setType(AstronautType type) {
    this.type = type;
  }

  public AstronautDetailedSerializerNoFlights status(AstronautStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public AstronautStatus getStatus() {
    return status;
  }

  public void setStatus(AstronautStatus status) {
    this.status = status;
  }

  public AstronautDetailedSerializerNoFlights agency(AgencySerializerMini agency) {
    this.agency = agency;
    return this;
  }

   /**
   * Get agency
   * @return agency
  **/
  @ApiModelProperty(value = "")
  public AgencySerializerMini getAgency() {
    return agency;
  }

  public void setAgency(AgencySerializerMini agency) {
    this.agency = agency;
  }

  public AstronautDetailedSerializerNoFlights dateOfBirth(LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Get dateOfBirth
   * @return dateOfBirth
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public AstronautDetailedSerializerNoFlights dateOfDeath(LocalDate dateOfDeath) {
    this.dateOfDeath = dateOfDeath;
    return this;
  }

   /**
   * Get dateOfDeath
   * @return dateOfDeath
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDateOfDeath() {
    return dateOfDeath;
  }

  public void setDateOfDeath(LocalDate dateOfDeath) {
    this.dateOfDeath = dateOfDeath;
  }

  public AstronautDetailedSerializerNoFlights nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public AstronautDetailedSerializerNoFlights twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * Get twitter
   * @return twitter
  **/
  @ApiModelProperty(value = "")
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public AstronautDetailedSerializerNoFlights instagram(String instagram) {
    this.instagram = instagram;
    return this;
  }

   /**
   * Get instagram
   * @return instagram
  **/
  @ApiModelProperty(value = "")
  public String getInstagram() {
    return instagram;
  }

  public void setInstagram(String instagram) {
    this.instagram = instagram;
  }

  public AstronautDetailedSerializerNoFlights bio(String bio) {
    this.bio = bio;
    return this;
  }

   /**
   * Get bio
   * @return bio
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

   /**
   * Get profileImage
   * @return profileImage
  **/
  @ApiModelProperty(value = "")
  public String getProfileImage() {
    return profileImage;
  }

  public AstronautDetailedSerializerNoFlights wiki(String wiki) {
    this.wiki = wiki;
    return this;
  }

   /**
   * Get wiki
   * @return wiki
  **/
  @ApiModelProperty(value = "")
  public String getWiki() {
    return wiki;
  }

  public void setWiki(String wiki) {
    this.wiki = wiki;
  }

   /**
   * Get lastFlight
   * @return lastFlight
  **/
  @ApiModelProperty(value = "")
  public String getLastFlight() {
    return lastFlight;
  }

   /**
   * Get firstFlight
   * @return firstFlight
  **/
  @ApiModelProperty(value = "")
  public String getFirstFlight() {
    return firstFlight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AstronautDetailedSerializerNoFlights astronautDetailedSerializerNoFlights = (AstronautDetailedSerializerNoFlights) o;
    return Objects.equals(this.id, astronautDetailedSerializerNoFlights.id) &&
        Objects.equals(this.url, astronautDetailedSerializerNoFlights.url) &&
        Objects.equals(this.name, astronautDetailedSerializerNoFlights.name) &&
        Objects.equals(this.type, astronautDetailedSerializerNoFlights.type) &&
        Objects.equals(this.status, astronautDetailedSerializerNoFlights.status) &&
        Objects.equals(this.agency, astronautDetailedSerializerNoFlights.agency) &&
        Objects.equals(this.dateOfBirth, astronautDetailedSerializerNoFlights.dateOfBirth) &&
        Objects.equals(this.dateOfDeath, astronautDetailedSerializerNoFlights.dateOfDeath) &&
        Objects.equals(this.nationality, astronautDetailedSerializerNoFlights.nationality) &&
        Objects.equals(this.twitter, astronautDetailedSerializerNoFlights.twitter) &&
        Objects.equals(this.instagram, astronautDetailedSerializerNoFlights.instagram) &&
        Objects.equals(this.bio, astronautDetailedSerializerNoFlights.bio) &&
        Objects.equals(this.profileImage, astronautDetailedSerializerNoFlights.profileImage) &&
        Objects.equals(this.wiki, astronautDetailedSerializerNoFlights.wiki) &&
        Objects.equals(this.lastFlight, astronautDetailedSerializerNoFlights.lastFlight) &&
        Objects.equals(this.firstFlight, astronautDetailedSerializerNoFlights.firstFlight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, name, type, status, agency, dateOfBirth, dateOfDeath, nationality, twitter, instagram, bio, profileImage, wiki, lastFlight, firstFlight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AstronautDetailedSerializerNoFlights {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    agency: ").append(toIndentedString(agency)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    dateOfDeath: ").append(toIndentedString(dateOfDeath)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    instagram: ").append(toIndentedString(instagram)).append("\n");
    sb.append("    bio: ").append(toIndentedString(bio)).append("\n");
    sb.append("    profileImage: ").append(toIndentedString(profileImage)).append("\n");
    sb.append("    wiki: ").append(toIndentedString(wiki)).append("\n");
    sb.append("    lastFlight: ").append(toIndentedString(lastFlight)).append("\n");
    sb.append("    firstFlight: ").append(toIndentedString(firstFlight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

