/*
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.LocalDate;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * LauncherConfigDetailSerializerForAgency
 */

public class LauncherConfigDetailSerializerForAgency {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("family")
  private String family = null;

  @SerializedName("full_name")
  private String fullName = null;

  @SerializedName("variant")
  private String variant = null;

  @SerializedName("alias")
  private String alias = null;

  @SerializedName("min_stage")
  private Integer minStage = null;

  @SerializedName("max_stage")
  private Integer maxStage = null;

  @SerializedName("length")
  private BigDecimal length = null;

  @SerializedName("diameter")
  private BigDecimal diameter = null;

  @SerializedName("maiden_flight")
  private LocalDate maidenFlight = null;

  @SerializedName("launch_mass")
  private Integer launchMass = null;

  @SerializedName("leo_capacity")
  private Integer leoCapacity = null;

  @SerializedName("gto_capacity")
  private Integer gtoCapacity = null;

  @SerializedName("to_thrust")
  private Integer toThrust = null;

  @SerializedName("apogee")
  private Integer apogee = null;

  @SerializedName("vehicle_range")
  private Integer vehicleRange = null;

  @SerializedName("image_url")
  private String imageUrl = null;

  @SerializedName("info_url")
  private String infoUrl = null;

  @SerializedName("wiki_url")
  private String wikiUrl = null;

  @SerializedName("consecutive_successful_launches")
  private Integer consecutiveSuccessfulLaunches = null;

  @SerializedName("successful_launches")
  private Integer successfulLaunches = null;

  @SerializedName("failed_launches")
  private Integer failedLaunches = null;

  @SerializedName("pending_launches")
  private Integer pendingLaunches = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public LauncherConfigDetailSerializerForAgency name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LauncherConfigDetailSerializerForAgency description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public LauncherConfigDetailSerializerForAgency family(String family) {
    this.family = family;
    return this;
  }

   /**
   * Get family
   * @return family
  **/
  @ApiModelProperty(value = "")
  public String getFamily() {
    return family;
  }

  public void setFamily(String family) {
    this.family = family;
  }

  public LauncherConfigDetailSerializerForAgency fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public LauncherConfigDetailSerializerForAgency variant(String variant) {
    this.variant = variant;
    return this;
  }

   /**
   * Get variant
   * @return variant
  **/
  @ApiModelProperty(value = "")
  public String getVariant() {
    return variant;
  }

  public void setVariant(String variant) {
    this.variant = variant;
  }

  public LauncherConfigDetailSerializerForAgency alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @ApiModelProperty(value = "")
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public LauncherConfigDetailSerializerForAgency minStage(Integer minStage) {
    this.minStage = minStage;
    return this;
  }

   /**
   * Get minStage
   * minimum: -2147483648
   * maximum: 2147483647
   * @return minStage
  **/
  @ApiModelProperty(value = "")
  public Integer getMinStage() {
    return minStage;
  }

  public void setMinStage(Integer minStage) {
    this.minStage = minStage;
  }

  public LauncherConfigDetailSerializerForAgency maxStage(Integer maxStage) {
    this.maxStage = maxStage;
    return this;
  }

   /**
   * Get maxStage
   * minimum: -2147483648
   * maximum: 2147483647
   * @return maxStage
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxStage() {
    return maxStage;
  }

  public void setMaxStage(Integer maxStage) {
    this.maxStage = maxStage;
  }

  public LauncherConfigDetailSerializerForAgency length(BigDecimal length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getLength() {
    return length;
  }

  public void setLength(BigDecimal length) {
    this.length = length;
  }

  public LauncherConfigDetailSerializerForAgency diameter(BigDecimal diameter) {
    this.diameter = diameter;
    return this;
  }

   /**
   * Get diameter
   * @return diameter
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDiameter() {
    return diameter;
  }

  public void setDiameter(BigDecimal diameter) {
    this.diameter = diameter;
  }

  public LauncherConfigDetailSerializerForAgency maidenFlight(LocalDate maidenFlight) {
    this.maidenFlight = maidenFlight;
    return this;
  }

   /**
   * Get maidenFlight
   * @return maidenFlight
  **/
  @ApiModelProperty(value = "")
  public LocalDate getMaidenFlight() {
    return maidenFlight;
  }

  public void setMaidenFlight(LocalDate maidenFlight) {
    this.maidenFlight = maidenFlight;
  }

  public LauncherConfigDetailSerializerForAgency launchMass(Integer launchMass) {
    this.launchMass = launchMass;
    return this;
  }

   /**
   * Get launchMass
   * minimum: -2147483648
   * maximum: 2147483647
   * @return launchMass
  **/
  @ApiModelProperty(value = "")
  public Integer getLaunchMass() {
    return launchMass;
  }

  public void setLaunchMass(Integer launchMass) {
    this.launchMass = launchMass;
  }

  public LauncherConfigDetailSerializerForAgency leoCapacity(Integer leoCapacity) {
    this.leoCapacity = leoCapacity;
    return this;
  }

   /**
   * Get leoCapacity
   * minimum: -2147483648
   * maximum: 2147483647
   * @return leoCapacity
  **/
  @ApiModelProperty(value = "")
  public Integer getLeoCapacity() {
    return leoCapacity;
  }

  public void setLeoCapacity(Integer leoCapacity) {
    this.leoCapacity = leoCapacity;
  }

  public LauncherConfigDetailSerializerForAgency gtoCapacity(Integer gtoCapacity) {
    this.gtoCapacity = gtoCapacity;
    return this;
  }

   /**
   * Get gtoCapacity
   * minimum: -2147483648
   * maximum: 2147483647
   * @return gtoCapacity
  **/
  @ApiModelProperty(value = "")
  public Integer getGtoCapacity() {
    return gtoCapacity;
  }

  public void setGtoCapacity(Integer gtoCapacity) {
    this.gtoCapacity = gtoCapacity;
  }

  public LauncherConfigDetailSerializerForAgency toThrust(Integer toThrust) {
    this.toThrust = toThrust;
    return this;
  }

   /**
   * Get toThrust
   * minimum: -2147483648
   * maximum: 2147483647
   * @return toThrust
  **/
  @ApiModelProperty(value = "")
  public Integer getToThrust() {
    return toThrust;
  }

  public void setToThrust(Integer toThrust) {
    this.toThrust = toThrust;
  }

  public LauncherConfigDetailSerializerForAgency apogee(Integer apogee) {
    this.apogee = apogee;
    return this;
  }

   /**
   * Get apogee
   * minimum: -2147483648
   * maximum: 2147483647
   * @return apogee
  **/
  @ApiModelProperty(value = "")
  public Integer getApogee() {
    return apogee;
  }

  public void setApogee(Integer apogee) {
    this.apogee = apogee;
  }

  public LauncherConfigDetailSerializerForAgency vehicleRange(Integer vehicleRange) {
    this.vehicleRange = vehicleRange;
    return this;
  }

   /**
   * Get vehicleRange
   * minimum: -2147483648
   * maximum: 2147483647
   * @return vehicleRange
  **/
  @ApiModelProperty(value = "")
  public Integer getVehicleRange() {
    return vehicleRange;
  }

  public void setVehicleRange(Integer vehicleRange) {
    this.vehicleRange = vehicleRange;
  }

   /**
   * Get imageUrl
   * @return imageUrl
  **/
  @ApiModelProperty(value = "")
  public String getImageUrl() {
    return imageUrl;
  }

  public LauncherConfigDetailSerializerForAgency infoUrl(String infoUrl) {
    this.infoUrl = infoUrl;
    return this;
  }

   /**
   * Get infoUrl
   * @return infoUrl
  **/
  @ApiModelProperty(value = "")
  public String getInfoUrl() {
    return infoUrl;
  }

  public void setInfoUrl(String infoUrl) {
    this.infoUrl = infoUrl;
  }

  public LauncherConfigDetailSerializerForAgency wikiUrl(String wikiUrl) {
    this.wikiUrl = wikiUrl;
    return this;
  }

   /**
   * Get wikiUrl
   * @return wikiUrl
  **/
  @ApiModelProperty(value = "")
  public String getWikiUrl() {
    return wikiUrl;
  }

  public void setWikiUrl(String wikiUrl) {
    this.wikiUrl = wikiUrl;
  }

   /**
   * Get consecutiveSuccessfulLaunches
   * @return consecutiveSuccessfulLaunches
  **/
  @ApiModelProperty(value = "")
  public Integer getConsecutiveSuccessfulLaunches() {
    return consecutiveSuccessfulLaunches;
  }

   /**
   * Get successfulLaunches
   * @return successfulLaunches
  **/
  @ApiModelProperty(value = "")
  public Integer getSuccessfulLaunches() {
    return successfulLaunches;
  }

   /**
   * Get failedLaunches
   * @return failedLaunches
  **/
  @ApiModelProperty(value = "")
  public Integer getFailedLaunches() {
    return failedLaunches;
  }

   /**
   * Get pendingLaunches
   * @return pendingLaunches
  **/
  @ApiModelProperty(value = "")
  public Integer getPendingLaunches() {
    return pendingLaunches;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LauncherConfigDetailSerializerForAgency launcherConfigDetailSerializerForAgency = (LauncherConfigDetailSerializerForAgency) o;
    return Objects.equals(this.id, launcherConfigDetailSerializerForAgency.id) &&
        Objects.equals(this.url, launcherConfigDetailSerializerForAgency.url) &&
        Objects.equals(this.name, launcherConfigDetailSerializerForAgency.name) &&
        Objects.equals(this.description, launcherConfigDetailSerializerForAgency.description) &&
        Objects.equals(this.family, launcherConfigDetailSerializerForAgency.family) &&
        Objects.equals(this.fullName, launcherConfigDetailSerializerForAgency.fullName) &&
        Objects.equals(this.variant, launcherConfigDetailSerializerForAgency.variant) &&
        Objects.equals(this.alias, launcherConfigDetailSerializerForAgency.alias) &&
        Objects.equals(this.minStage, launcherConfigDetailSerializerForAgency.minStage) &&
        Objects.equals(this.maxStage, launcherConfigDetailSerializerForAgency.maxStage) &&
        Objects.equals(this.length, launcherConfigDetailSerializerForAgency.length) &&
        Objects.equals(this.diameter, launcherConfigDetailSerializerForAgency.diameter) &&
        Objects.equals(this.maidenFlight, launcherConfigDetailSerializerForAgency.maidenFlight) &&
        Objects.equals(this.launchMass, launcherConfigDetailSerializerForAgency.launchMass) &&
        Objects.equals(this.leoCapacity, launcherConfigDetailSerializerForAgency.leoCapacity) &&
        Objects.equals(this.gtoCapacity, launcherConfigDetailSerializerForAgency.gtoCapacity) &&
        Objects.equals(this.toThrust, launcherConfigDetailSerializerForAgency.toThrust) &&
        Objects.equals(this.apogee, launcherConfigDetailSerializerForAgency.apogee) &&
        Objects.equals(this.vehicleRange, launcherConfigDetailSerializerForAgency.vehicleRange) &&
        Objects.equals(this.imageUrl, launcherConfigDetailSerializerForAgency.imageUrl) &&
        Objects.equals(this.infoUrl, launcherConfigDetailSerializerForAgency.infoUrl) &&
        Objects.equals(this.wikiUrl, launcherConfigDetailSerializerForAgency.wikiUrl) &&
        Objects.equals(this.consecutiveSuccessfulLaunches, launcherConfigDetailSerializerForAgency.consecutiveSuccessfulLaunches) &&
        Objects.equals(this.successfulLaunches, launcherConfigDetailSerializerForAgency.successfulLaunches) &&
        Objects.equals(this.failedLaunches, launcherConfigDetailSerializerForAgency.failedLaunches) &&
        Objects.equals(this.pendingLaunches, launcherConfigDetailSerializerForAgency.pendingLaunches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, name, description, family, fullName, variant, alias, minStage, maxStage, length, diameter, maidenFlight, launchMass, leoCapacity, gtoCapacity, toThrust, apogee, vehicleRange, imageUrl, infoUrl, wikiUrl, consecutiveSuccessfulLaunches, successfulLaunches, failedLaunches, pendingLaunches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LauncherConfigDetailSerializerForAgency {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    minStage: ").append(toIndentedString(minStage)).append("\n");
    sb.append("    maxStage: ").append(toIndentedString(maxStage)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    diameter: ").append(toIndentedString(diameter)).append("\n");
    sb.append("    maidenFlight: ").append(toIndentedString(maidenFlight)).append("\n");
    sb.append("    launchMass: ").append(toIndentedString(launchMass)).append("\n");
    sb.append("    leoCapacity: ").append(toIndentedString(leoCapacity)).append("\n");
    sb.append("    gtoCapacity: ").append(toIndentedString(gtoCapacity)).append("\n");
    sb.append("    toThrust: ").append(toIndentedString(toThrust)).append("\n");
    sb.append("    apogee: ").append(toIndentedString(apogee)).append("\n");
    sb.append("    vehicleRange: ").append(toIndentedString(vehicleRange)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    infoUrl: ").append(toIndentedString(infoUrl)).append("\n");
    sb.append("    wikiUrl: ").append(toIndentedString(wikiUrl)).append("\n");
    sb.append("    consecutiveSuccessfulLaunches: ").append(toIndentedString(consecutiveSuccessfulLaunches)).append("\n");
    sb.append("    successfulLaunches: ").append(toIndentedString(successfulLaunches)).append("\n");
    sb.append("    failedLaunches: ").append(toIndentedString(failedLaunches)).append("\n");
    sb.append("    pendingLaunches: ").append(toIndentedString(pendingLaunches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

