/*
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * PadSerializerNoLocation
 */
public class PadSerializerNoLocation {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("agency_id")
  private Integer agencyId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("info_url")
  private String infoUrl = null;

  @SerializedName("wiki_url")
  private String wikiUrl = null;

  @SerializedName("map_url")
  private String mapUrl = null;

  @SerializedName("latitude")
  private String latitude = null;

  @SerializedName("longitude")
  private String longitude = null;

  @SerializedName("map_image")
  private String mapImage = null;

  @SerializedName("total_launch_count")
  private String totalLaunchCount = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public PadSerializerNoLocation agencyId(Integer agencyId) {
    this.agencyId = agencyId;
    return this;
  }

   /**
   * Get agencyId
   * minimum: -2147483648
   * maximum: 2147483647
   * @return agencyId
  **/
  @ApiModelProperty(value = "")
  public Integer getAgencyId() {
    return agencyId;
  }

  public void setAgencyId(Integer agencyId) {
    this.agencyId = agencyId;
  }

  public PadSerializerNoLocation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PadSerializerNoLocation infoUrl(String infoUrl) {
    this.infoUrl = infoUrl;
    return this;
  }

   /**
   * Get infoUrl
   * @return infoUrl
  **/
  @ApiModelProperty(value = "")
  public String getInfoUrl() {
    return infoUrl;
  }

  public void setInfoUrl(String infoUrl) {
    this.infoUrl = infoUrl;
  }

  public PadSerializerNoLocation wikiUrl(String wikiUrl) {
    this.wikiUrl = wikiUrl;
    return this;
  }

   /**
   * Get wikiUrl
   * @return wikiUrl
  **/
  @ApiModelProperty(value = "")
  public String getWikiUrl() {
    return wikiUrl;
  }

  public void setWikiUrl(String wikiUrl) {
    this.wikiUrl = wikiUrl;
  }

  public PadSerializerNoLocation mapUrl(String mapUrl) {
    this.mapUrl = mapUrl;
    return this;
  }

   /**
   * Get mapUrl
   * @return mapUrl
  **/
  @ApiModelProperty(value = "")
  public String getMapUrl() {
    return mapUrl;
  }

  public void setMapUrl(String mapUrl) {
    this.mapUrl = mapUrl;
  }

  public PadSerializerNoLocation latitude(String latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @ApiModelProperty(value = "")
  public String getLatitude() {
    return latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  public PadSerializerNoLocation longitude(String longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @ApiModelProperty(value = "")
  public String getLongitude() {
    return longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

   /**
   * Get mapImage
   * @return mapImage
  **/
  @ApiModelProperty(value = "")
  public String getMapImage() {
    return mapImage;
  }

   /**
   * Get totalLaunchCount
   * @return totalLaunchCount
  **/
  @ApiModelProperty(value = "")
  public String getTotalLaunchCount() {
    return totalLaunchCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PadSerializerNoLocation padSerializerNoLocation = (PadSerializerNoLocation) o;
    return Objects.equals(this.id, padSerializerNoLocation.id) &&
        Objects.equals(this.url, padSerializerNoLocation.url) &&
        Objects.equals(this.agencyId, padSerializerNoLocation.agencyId) &&
        Objects.equals(this.name, padSerializerNoLocation.name) &&
        Objects.equals(this.infoUrl, padSerializerNoLocation.infoUrl) &&
        Objects.equals(this.wikiUrl, padSerializerNoLocation.wikiUrl) &&
        Objects.equals(this.mapUrl, padSerializerNoLocation.mapUrl) &&
        Objects.equals(this.latitude, padSerializerNoLocation.latitude) &&
        Objects.equals(this.longitude, padSerializerNoLocation.longitude) &&
        Objects.equals(this.mapImage, padSerializerNoLocation.mapImage) &&
        Objects.equals(this.totalLaunchCount, padSerializerNoLocation.totalLaunchCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, agencyId, name, infoUrl, wikiUrl, mapUrl, latitude, longitude, mapImage, totalLaunchCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PadSerializerNoLocation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    agencyId: ").append(toIndentedString(agencyId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    infoUrl: ").append(toIndentedString(infoUrl)).append("\n");
    sb.append("    wikiUrl: ").append(toIndentedString(wikiUrl)).append("\n");
    sb.append("    mapUrl: ").append(toIndentedString(mapUrl)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    mapImage: ").append(toIndentedString(mapImage)).append("\n");
    sb.append("    totalLaunchCount: ").append(toIndentedString(totalLaunchCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

