/*
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package models;

import com.google.gson.annotations.SerializedName;

import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RocketDetailed
 */

public class RocketDetailed {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("configuration")
  private LauncherConfigDetail _configuration = null;

  @SerializedName("launcher_stage")
  private List<FirstStage> launcherStage = null;

  @SerializedName("spacecraft_stage")
  private SpacecraftFlightDetailedSerializerForLaunch spacecraftStage = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public RocketDetailed _configuration(LauncherConfigDetail _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @ApiModelProperty(value = "")
  public LauncherConfigDetail getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(LauncherConfigDetail _configuration) {
    this._configuration = _configuration;
  }

   /**
   * Get launcherStage
   * @return launcherStage
  **/
  @ApiModelProperty(value = "")
  public List<FirstStage> getLauncherStage() {
    return launcherStage;
  }

  public RocketDetailed spacecraftStage(SpacecraftFlightDetailedSerializerForLaunch spacecraftStage) {
    this.spacecraftStage = spacecraftStage;
    return this;
  }

   /**
   * Get spacecraftStage
   * @return spacecraftStage
  **/
  @ApiModelProperty(value = "")
  public SpacecraftFlightDetailedSerializerForLaunch getSpacecraftStage() {
    return spacecraftStage;
  }

  public void setSpacecraftStage(SpacecraftFlightDetailedSerializerForLaunch spacecraftStage) {
    this.spacecraftStage = spacecraftStage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RocketDetailed rocketDetailed = (RocketDetailed) o;
    return Objects.equals(this.id, rocketDetailed.id) &&
        Objects.equals(this._configuration, rocketDetailed._configuration) &&
        Objects.equals(this.launcherStage, rocketDetailed.launcherStage) &&
        Objects.equals(this.spacecraftStage, rocketDetailed.spacecraftStage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _configuration, launcherStage, spacecraftStage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RocketDetailed {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    launcherStage: ").append(toIndentedString(launcherStage)).append("\n");
    sb.append("    spacecraftStage: ").append(toIndentedString(spacecraftStage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

