/*
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.LocalDate;

import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * SpaceStation
 */

public class SpaceStation {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private SpaceStationStatus status = null;

  @SerializedName("type")
  private SpaceStationType type = null;

  @SerializedName("founded")
  private LocalDate founded = null;

  @SerializedName("deorbited")
  private LocalDate deorbited = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("orbit")
  private String orbit = null;

  @SerializedName("owners")
  private List<AgencyList> owners = null;

  @SerializedName("active_expedition")
  private List<ExpeditionSerializerForSpacestation> activeExpedition = null;

  @SerializedName("image_url")
  private String imageUrl = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public SpaceStation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SpaceStation status(SpaceStationStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public SpaceStationStatus getStatus() {
    return status;
  }

  public void setStatus(SpaceStationStatus status) {
    this.status = status;
  }

  public SpaceStation type(SpaceStationType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public SpaceStationType getType() {
    return type;
  }

  public void setType(SpaceStationType type) {
    this.type = type;
  }

  public SpaceStation founded(LocalDate founded) {
    this.founded = founded;
    return this;
  }

   /**
   * Get founded
   * @return founded
  **/
  @ApiModelProperty(required = true, value = "")
  public LocalDate getFounded() {
    return founded;
  }

  public void setFounded(LocalDate founded) {
    this.founded = founded;
  }

  public SpaceStation deorbited(LocalDate deorbited) {
    this.deorbited = deorbited;
    return this;
  }

   /**
   * Get deorbited
   * @return deorbited
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDeorbited() {
    return deorbited;
  }

  public void setDeorbited(LocalDate deorbited) {
    this.deorbited = deorbited;
  }

  public SpaceStation description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

   /**
   * Get orbit
   * @return orbit
  **/
  @ApiModelProperty(value = "")
  public String getOrbit() {
    return orbit;
  }

   /**
   * Get owners
   * @return owners
  **/
  @ApiModelProperty(value = "")
  public List<AgencyList> getOwners() {
    return owners;
  }

   /**
   * Get activeExpedition
   * @return activeExpedition
  **/
  @ApiModelProperty(value = "")
  public List<ExpeditionSerializerForSpacestation> getActiveExpedition() {
    return activeExpedition;
  }

   /**
   * Get imageUrl
   * @return imageUrl
  **/
  @ApiModelProperty(value = "")
  public String getImageUrl() {
    return imageUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpaceStation spaceStation = (SpaceStation) o;
    return Objects.equals(this.id, spaceStation.id) &&
        Objects.equals(this.url, spaceStation.url) &&
        Objects.equals(this.name, spaceStation.name) &&
        Objects.equals(this.status, spaceStation.status) &&
        Objects.equals(this.type, spaceStation.type) &&
        Objects.equals(this.founded, spaceStation.founded) &&
        Objects.equals(this.deorbited, spaceStation.deorbited) &&
        Objects.equals(this.description, spaceStation.description) &&
        Objects.equals(this.orbit, spaceStation.orbit) &&
        Objects.equals(this.owners, spaceStation.owners) &&
        Objects.equals(this.activeExpedition, spaceStation.activeExpedition) &&
        Objects.equals(this.imageUrl, spaceStation.imageUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, name, status, type, founded, deorbited, description, orbit, owners, activeExpedition, imageUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpaceStation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    founded: ").append(toIndentedString(founded)).append("\n");
    sb.append("    deorbited: ").append(toIndentedString(deorbited)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    orbit: ").append(toIndentedString(orbit)).append("\n");
    sb.append("    owners: ").append(toIndentedString(owners)).append("\n");
    sb.append("    activeExpedition: ").append(toIndentedString(activeExpedition)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

