/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AgencySerializerDetailedCommon {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("featured")
  private Boolean featured = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("country_code")
  private String countryCode = null;
  @SerializedName("abbrev")
  private String abbrev = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("administrator")
  private String administrator = null;
  @SerializedName("founding_year")
  private String foundingYear = null;
  @SerializedName("launchers")
  private String launchers = null;
  @SerializedName("spacecraft")
  private String spacecraft = null;
  @SerializedName("launch_library_url")
  private String launchLibraryUrl = null;
  @SerializedName("total_launch_count")
  private String totalLaunchCount = null;
  @SerializedName("consecutive_successful_launches")
  private String consecutiveSuccessfulLaunches = null;
  @SerializedName("successful_launches")
  private String successfulLaunches = null;
  @SerializedName("failed_launches")
  private String failedLaunches = null;
  @SerializedName("pending_launches")
  private String pendingLaunches = null;
  @SerializedName("consecutive_successful_landings")
  private String consecutiveSuccessfulLandings = null;
  @SerializedName("successful_landings")
  private String successfulLandings = null;
  @SerializedName("failed_landings")
  private String failedLandings = null;
  @SerializedName("attempted_landings")
  private String attemptedLandings = null;
  @SerializedName("info_url")
  private String infoUrl = null;
  @SerializedName("wiki_url")
  private String wikiUrl = null;
  @SerializedName("logo_url")
  private String logoUrl = null;
  @SerializedName("image_url")
  private String imageUrl = null;
  @SerializedName("nation_url")
  private String nationUrl = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getFeatured() {
    return featured;
  }
  public void setFeatured(Boolean featured) {
    this.featured = featured;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAbbrev() {
    return abbrev;
  }
  public void setAbbrev(String abbrev) {
    this.abbrev = abbrev;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAdministrator() {
    return administrator;
  }
  public void setAdministrator(String administrator) {
    this.administrator = administrator;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFoundingYear() {
    return foundingYear;
  }
  public void setFoundingYear(String foundingYear) {
    this.foundingYear = foundingYear;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLaunchers() {
    return launchers;
  }
  public void setLaunchers(String launchers) {
    this.launchers = launchers;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSpacecraft() {
    return spacecraft;
  }
  public void setSpacecraft(String spacecraft) {
    this.spacecraft = spacecraft;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLaunchLibraryUrl() {
    return launchLibraryUrl;
  }
  public void setLaunchLibraryUrl(String launchLibraryUrl) {
    this.launchLibraryUrl = launchLibraryUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTotalLaunchCount() {
    return totalLaunchCount;
  }
  public void setTotalLaunchCount(String totalLaunchCount) {
    this.totalLaunchCount = totalLaunchCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getConsecutiveSuccessfulLaunches() {
    return consecutiveSuccessfulLaunches;
  }
  public void setConsecutiveSuccessfulLaunches(String consecutiveSuccessfulLaunches) {
    this.consecutiveSuccessfulLaunches = consecutiveSuccessfulLaunches;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSuccessfulLaunches() {
    return successfulLaunches;
  }
  public void setSuccessfulLaunches(String successfulLaunches) {
    this.successfulLaunches = successfulLaunches;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFailedLaunches() {
    return failedLaunches;
  }
  public void setFailedLaunches(String failedLaunches) {
    this.failedLaunches = failedLaunches;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPendingLaunches() {
    return pendingLaunches;
  }
  public void setPendingLaunches(String pendingLaunches) {
    this.pendingLaunches = pendingLaunches;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getConsecutiveSuccessfulLandings() {
    return consecutiveSuccessfulLandings;
  }
  public void setConsecutiveSuccessfulLandings(String consecutiveSuccessfulLandings) {
    this.consecutiveSuccessfulLandings = consecutiveSuccessfulLandings;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSuccessfulLandings() {
    return successfulLandings;
  }
  public void setSuccessfulLandings(String successfulLandings) {
    this.successfulLandings = successfulLandings;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFailedLandings() {
    return failedLandings;
  }
  public void setFailedLandings(String failedLandings) {
    this.failedLandings = failedLandings;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAttemptedLandings() {
    return attemptedLandings;
  }
  public void setAttemptedLandings(String attemptedLandings) {
    this.attemptedLandings = attemptedLandings;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInfoUrl() {
    return infoUrl;
  }
  public void setInfoUrl(String infoUrl) {
    this.infoUrl = infoUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWikiUrl() {
    return wikiUrl;
  }
  public void setWikiUrl(String wikiUrl) {
    this.wikiUrl = wikiUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLogoUrl() {
    return logoUrl;
  }
  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getImageUrl() {
    return imageUrl;
  }
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNationUrl() {
    return nationUrl;
  }
  public void setNationUrl(String nationUrl) {
    this.nationUrl = nationUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgencySerializerDetailedCommon agencySerializerDetailedCommon = (AgencySerializerDetailedCommon) o;
    return (this.id == null ? agencySerializerDetailedCommon.id == null : this.id.equals(agencySerializerDetailedCommon.id)) &&
        (this.url == null ? agencySerializerDetailedCommon.url == null : this.url.equals(agencySerializerDetailedCommon.url)) &&
        (this.name == null ? agencySerializerDetailedCommon.name == null : this.name.equals(agencySerializerDetailedCommon.name)) &&
        (this.featured == null ? agencySerializerDetailedCommon.featured == null : this.featured.equals(agencySerializerDetailedCommon.featured)) &&
        (this.type == null ? agencySerializerDetailedCommon.type == null : this.type.equals(agencySerializerDetailedCommon.type)) &&
        (this.countryCode == null ? agencySerializerDetailedCommon.countryCode == null : this.countryCode.equals(agencySerializerDetailedCommon.countryCode)) &&
        (this.abbrev == null ? agencySerializerDetailedCommon.abbrev == null : this.abbrev.equals(agencySerializerDetailedCommon.abbrev)) &&
        (this.description == null ? agencySerializerDetailedCommon.description == null : this.description.equals(agencySerializerDetailedCommon.description)) &&
        (this.administrator == null ? agencySerializerDetailedCommon.administrator == null : this.administrator.equals(agencySerializerDetailedCommon.administrator)) &&
        (this.foundingYear == null ? agencySerializerDetailedCommon.foundingYear == null : this.foundingYear.equals(agencySerializerDetailedCommon.foundingYear)) &&
        (this.launchers == null ? agencySerializerDetailedCommon.launchers == null : this.launchers.equals(agencySerializerDetailedCommon.launchers)) &&
        (this.spacecraft == null ? agencySerializerDetailedCommon.spacecraft == null : this.spacecraft.equals(agencySerializerDetailedCommon.spacecraft)) &&
        (this.launchLibraryUrl == null ? agencySerializerDetailedCommon.launchLibraryUrl == null : this.launchLibraryUrl.equals(agencySerializerDetailedCommon.launchLibraryUrl)) &&
        (this.totalLaunchCount == null ? agencySerializerDetailedCommon.totalLaunchCount == null : this.totalLaunchCount.equals(agencySerializerDetailedCommon.totalLaunchCount)) &&
        (this.consecutiveSuccessfulLaunches == null ? agencySerializerDetailedCommon.consecutiveSuccessfulLaunches == null : this.consecutiveSuccessfulLaunches.equals(agencySerializerDetailedCommon.consecutiveSuccessfulLaunches)) &&
        (this.successfulLaunches == null ? agencySerializerDetailedCommon.successfulLaunches == null : this.successfulLaunches.equals(agencySerializerDetailedCommon.successfulLaunches)) &&
        (this.failedLaunches == null ? agencySerializerDetailedCommon.failedLaunches == null : this.failedLaunches.equals(agencySerializerDetailedCommon.failedLaunches)) &&
        (this.pendingLaunches == null ? agencySerializerDetailedCommon.pendingLaunches == null : this.pendingLaunches.equals(agencySerializerDetailedCommon.pendingLaunches)) &&
        (this.consecutiveSuccessfulLandings == null ? agencySerializerDetailedCommon.consecutiveSuccessfulLandings == null : this.consecutiveSuccessfulLandings.equals(agencySerializerDetailedCommon.consecutiveSuccessfulLandings)) &&
        (this.successfulLandings == null ? agencySerializerDetailedCommon.successfulLandings == null : this.successfulLandings.equals(agencySerializerDetailedCommon.successfulLandings)) &&
        (this.failedLandings == null ? agencySerializerDetailedCommon.failedLandings == null : this.failedLandings.equals(agencySerializerDetailedCommon.failedLandings)) &&
        (this.attemptedLandings == null ? agencySerializerDetailedCommon.attemptedLandings == null : this.attemptedLandings.equals(agencySerializerDetailedCommon.attemptedLandings)) &&
        (this.infoUrl == null ? agencySerializerDetailedCommon.infoUrl == null : this.infoUrl.equals(agencySerializerDetailedCommon.infoUrl)) &&
        (this.wikiUrl == null ? agencySerializerDetailedCommon.wikiUrl == null : this.wikiUrl.equals(agencySerializerDetailedCommon.wikiUrl)) &&
        (this.logoUrl == null ? agencySerializerDetailedCommon.logoUrl == null : this.logoUrl.equals(agencySerializerDetailedCommon.logoUrl)) &&
        (this.imageUrl == null ? agencySerializerDetailedCommon.imageUrl == null : this.imageUrl.equals(agencySerializerDetailedCommon.imageUrl)) &&
        (this.nationUrl == null ? agencySerializerDetailedCommon.nationUrl == null : this.nationUrl.equals(agencySerializerDetailedCommon.nationUrl));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.featured == null ? 0: this.featured.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.abbrev == null ? 0: this.abbrev.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.administrator == null ? 0: this.administrator.hashCode());
    result = 31 * result + (this.foundingYear == null ? 0: this.foundingYear.hashCode());
    result = 31 * result + (this.launchers == null ? 0: this.launchers.hashCode());
    result = 31 * result + (this.spacecraft == null ? 0: this.spacecraft.hashCode());
    result = 31 * result + (this.launchLibraryUrl == null ? 0: this.launchLibraryUrl.hashCode());
    result = 31 * result + (this.totalLaunchCount == null ? 0: this.totalLaunchCount.hashCode());
    result = 31 * result + (this.consecutiveSuccessfulLaunches == null ? 0: this.consecutiveSuccessfulLaunches.hashCode());
    result = 31 * result + (this.successfulLaunches == null ? 0: this.successfulLaunches.hashCode());
    result = 31 * result + (this.failedLaunches == null ? 0: this.failedLaunches.hashCode());
    result = 31 * result + (this.pendingLaunches == null ? 0: this.pendingLaunches.hashCode());
    result = 31 * result + (this.consecutiveSuccessfulLandings == null ? 0: this.consecutiveSuccessfulLandings.hashCode());
    result = 31 * result + (this.successfulLandings == null ? 0: this.successfulLandings.hashCode());
    result = 31 * result + (this.failedLandings == null ? 0: this.failedLandings.hashCode());
    result = 31 * result + (this.attemptedLandings == null ? 0: this.attemptedLandings.hashCode());
    result = 31 * result + (this.infoUrl == null ? 0: this.infoUrl.hashCode());
    result = 31 * result + (this.wikiUrl == null ? 0: this.wikiUrl.hashCode());
    result = 31 * result + (this.logoUrl == null ? 0: this.logoUrl.hashCode());
    result = 31 * result + (this.imageUrl == null ? 0: this.imageUrl.hashCode());
    result = 31 * result + (this.nationUrl == null ? 0: this.nationUrl.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgencySerializerDetailedCommon {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  featured: ").append(featured).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  abbrev: ").append(abbrev).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  administrator: ").append(administrator).append("\n");
    sb.append("  foundingYear: ").append(foundingYear).append("\n");
    sb.append("  launchers: ").append(launchers).append("\n");
    sb.append("  spacecraft: ").append(spacecraft).append("\n");
    sb.append("  launchLibraryUrl: ").append(launchLibraryUrl).append("\n");
    sb.append("  totalLaunchCount: ").append(totalLaunchCount).append("\n");
    sb.append("  consecutiveSuccessfulLaunches: ").append(consecutiveSuccessfulLaunches).append("\n");
    sb.append("  successfulLaunches: ").append(successfulLaunches).append("\n");
    sb.append("  failedLaunches: ").append(failedLaunches).append("\n");
    sb.append("  pendingLaunches: ").append(pendingLaunches).append("\n");
    sb.append("  consecutiveSuccessfulLandings: ").append(consecutiveSuccessfulLandings).append("\n");
    sb.append("  successfulLandings: ").append(successfulLandings).append("\n");
    sb.append("  failedLandings: ").append(failedLandings).append("\n");
    sb.append("  attemptedLandings: ").append(attemptedLandings).append("\n");
    sb.append("  infoUrl: ").append(infoUrl).append("\n");
    sb.append("  wikiUrl: ").append(wikiUrl).append("\n");
    sb.append("  logoUrl: ").append(logoUrl).append("\n");
    sb.append("  imageUrl: ").append(imageUrl).append("\n");
    sb.append("  nationUrl: ").append(nationUrl).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
