/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Agency {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("featured")
  private Boolean featured = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("country_code")
  private String countryCode = null;
  @SerializedName("abbrev")
  private String abbrev = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("administrator")
  private String administrator = null;
  @SerializedName("founding_year")
  private String foundingYear = null;
  @SerializedName("launchers")
  private String launchers = null;
  @SerializedName("spacecraft")
  private String spacecraft = null;
  @SerializedName("parent")
  private String parent = null;
  @SerializedName("image_url")
  private String imageUrl = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getFeatured() {
    return featured;
  }
  public void setFeatured(Boolean featured) {
    this.featured = featured;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAbbrev() {
    return abbrev;
  }
  public void setAbbrev(String abbrev) {
    this.abbrev = abbrev;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAdministrator() {
    return administrator;
  }
  public void setAdministrator(String administrator) {
    this.administrator = administrator;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFoundingYear() {
    return foundingYear;
  }
  public void setFoundingYear(String foundingYear) {
    this.foundingYear = foundingYear;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLaunchers() {
    return launchers;
  }
  public void setLaunchers(String launchers) {
    this.launchers = launchers;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSpacecraft() {
    return spacecraft;
  }
  public void setSpacecraft(String spacecraft) {
    this.spacecraft = spacecraft;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getParent() {
    return parent;
  }
  public void setParent(String parent) {
    this.parent = parent;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getImageUrl() {
    return imageUrl;
  }
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Agency agency = (Agency) o;
    return (this.id == null ? agency.id == null : this.id.equals(agency.id)) &&
        (this.url == null ? agency.url == null : this.url.equals(agency.url)) &&
        (this.name == null ? agency.name == null : this.name.equals(agency.name)) &&
        (this.featured == null ? agency.featured == null : this.featured.equals(agency.featured)) &&
        (this.type == null ? agency.type == null : this.type.equals(agency.type)) &&
        (this.countryCode == null ? agency.countryCode == null : this.countryCode.equals(agency.countryCode)) &&
        (this.abbrev == null ? agency.abbrev == null : this.abbrev.equals(agency.abbrev)) &&
        (this.description == null ? agency.description == null : this.description.equals(agency.description)) &&
        (this.administrator == null ? agency.administrator == null : this.administrator.equals(agency.administrator)) &&
        (this.foundingYear == null ? agency.foundingYear == null : this.foundingYear.equals(agency.foundingYear)) &&
        (this.launchers == null ? agency.launchers == null : this.launchers.equals(agency.launchers)) &&
        (this.spacecraft == null ? agency.spacecraft == null : this.spacecraft.equals(agency.spacecraft)) &&
        (this.parent == null ? agency.parent == null : this.parent.equals(agency.parent)) &&
        (this.imageUrl == null ? agency.imageUrl == null : this.imageUrl.equals(agency.imageUrl));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.featured == null ? 0: this.featured.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.abbrev == null ? 0: this.abbrev.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.administrator == null ? 0: this.administrator.hashCode());
    result = 31 * result + (this.foundingYear == null ? 0: this.foundingYear.hashCode());
    result = 31 * result + (this.launchers == null ? 0: this.launchers.hashCode());
    result = 31 * result + (this.spacecraft == null ? 0: this.spacecraft.hashCode());
    result = 31 * result + (this.parent == null ? 0: this.parent.hashCode());
    result = 31 * result + (this.imageUrl == null ? 0: this.imageUrl.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Agency {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  featured: ").append(featured).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  abbrev: ").append(abbrev).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  administrator: ").append(administrator).append("\n");
    sb.append("  foundingYear: ").append(foundingYear).append("\n");
    sb.append("  launchers: ").append(launchers).append("\n");
    sb.append("  spacecraft: ").append(spacecraft).append("\n");
    sb.append("  parent: ").append(parent).append("\n");
    sb.append("  imageUrl: ").append(imageUrl).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
