/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Astronaut;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AstronautFlightForExpedition {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("role")
  private String role = null;
  @SerializedName("astronaut")
  private Astronaut astronaut = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRole() {
    return role;
  }
  public void setRole(String role) {
    this.role = role;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Astronaut getAstronaut() {
    return astronaut;
  }
  public void setAstronaut(Astronaut astronaut) {
    this.astronaut = astronaut;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AstronautFlightForExpedition astronautFlightForExpedition = (AstronautFlightForExpedition) o;
    return (this.id == null ? astronautFlightForExpedition.id == null : this.id.equals(astronautFlightForExpedition.id)) &&
        (this.role == null ? astronautFlightForExpedition.role == null : this.role.equals(astronautFlightForExpedition.role)) &&
        (this.astronaut == null ? astronautFlightForExpedition.astronaut == null : this.astronaut.equals(astronautFlightForExpedition.astronaut));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.role == null ? 0: this.role.hashCode());
    result = 31 * result + (this.astronaut == null ? 0: this.astronaut.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AstronautFlightForExpedition {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  role: ").append(role).append("\n");
    sb.append("  astronaut: ").append(astronaut).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
