/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.AgencySerializerDetailedCommon;
import io.swagger.client.model.Program;
import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LauncherConfigDetail {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("launch_library_id")
  private Integer launchLibraryId = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("family")
  private String family = null;
  @SerializedName("full_name")
  private String fullName = null;
  @SerializedName("manufacturer")
  private AgencySerializerDetailedCommon manufacturer = null;
  @SerializedName("program")
  private List<Program> program = null;
  @SerializedName("variant")
  private String variant = null;
  @SerializedName("alias")
  private String alias = null;
  @SerializedName("min_stage")
  private Integer minStage = null;
  @SerializedName("max_stage")
  private Integer maxStage = null;
  @SerializedName("length")
  private BigDecimal length = null;
  @SerializedName("diameter")
  private BigDecimal diameter = null;
  @SerializedName("maiden_flight")
  private Date maidenFlight = null;
  @SerializedName("launch_mass")
  private Integer launchMass = null;
  @SerializedName("leo_capacity")
  private Integer leoCapacity = null;
  @SerializedName("gto_capacity")
  private Integer gtoCapacity = null;
  @SerializedName("to_thrust")
  private Integer toThrust = null;
  @SerializedName("apogee")
  private Integer apogee = null;
  @SerializedName("vehicle_range")
  private Integer vehicleRange = null;
  @SerializedName("image_url")
  private String imageUrl = null;
  @SerializedName("info_url")
  private String infoUrl = null;
  @SerializedName("wiki_url")
  private String wikiUrl = null;
  @SerializedName("total_launch_count")
  private String totalLaunchCount = null;
  @SerializedName("consecutive_successful_launches")
  private String consecutiveSuccessfulLaunches = null;
  @SerializedName("successful_launches")
  private String successfulLaunches = null;
  @SerializedName("failed_launches")
  private String failedLaunches = null;
  @SerializedName("pending_launches")
  private String pendingLaunches = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getLaunchLibraryId() {
    return launchLibraryId;
  }
  public void setLaunchLibraryId(Integer launchLibraryId) {
    this.launchLibraryId = launchLibraryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFamily() {
    return family;
  }
  public void setFamily(String family) {
    this.family = family;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFullName() {
    return fullName;
  }
  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public AgencySerializerDetailedCommon getManufacturer() {
    return manufacturer;
  }
  public void setManufacturer(AgencySerializerDetailedCommon manufacturer) {
    this.manufacturer = manufacturer;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Program> getProgram() {
    return program;
  }
  public void setProgram(List<Program> program) {
    this.program = program;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVariant() {
    return variant;
  }
  public void setVariant(String variant) {
    this.variant = variant;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAlias() {
    return alias;
  }
  public void setAlias(String alias) {
    this.alias = alias;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getMinStage() {
    return minStage;
  }
  public void setMinStage(Integer minStage) {
    this.minStage = minStage;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxStage() {
    return maxStage;
  }
  public void setMaxStage(Integer maxStage) {
    this.maxStage = maxStage;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getLength() {
    return length;
  }
  public void setLength(BigDecimal length) {
    this.length = length;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getDiameter() {
    return diameter;
  }
  public void setDiameter(BigDecimal diameter) {
    this.diameter = diameter;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getMaidenFlight() {
    return maidenFlight;
  }
  public void setMaidenFlight(Date maidenFlight) {
    this.maidenFlight = maidenFlight;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getLaunchMass() {
    return launchMass;
  }
  public void setLaunchMass(Integer launchMass) {
    this.launchMass = launchMass;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getLeoCapacity() {
    return leoCapacity;
  }
  public void setLeoCapacity(Integer leoCapacity) {
    this.leoCapacity = leoCapacity;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getGtoCapacity() {
    return gtoCapacity;
  }
  public void setGtoCapacity(Integer gtoCapacity) {
    this.gtoCapacity = gtoCapacity;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getToThrust() {
    return toThrust;
  }
  public void setToThrust(Integer toThrust) {
    this.toThrust = toThrust;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getApogee() {
    return apogee;
  }
  public void setApogee(Integer apogee) {
    this.apogee = apogee;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getVehicleRange() {
    return vehicleRange;
  }
  public void setVehicleRange(Integer vehicleRange) {
    this.vehicleRange = vehicleRange;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getImageUrl() {
    return imageUrl;
  }
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInfoUrl() {
    return infoUrl;
  }
  public void setInfoUrl(String infoUrl) {
    this.infoUrl = infoUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWikiUrl() {
    return wikiUrl;
  }
  public void setWikiUrl(String wikiUrl) {
    this.wikiUrl = wikiUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTotalLaunchCount() {
    return totalLaunchCount;
  }
  public void setTotalLaunchCount(String totalLaunchCount) {
    this.totalLaunchCount = totalLaunchCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getConsecutiveSuccessfulLaunches() {
    return consecutiveSuccessfulLaunches;
  }
  public void setConsecutiveSuccessfulLaunches(String consecutiveSuccessfulLaunches) {
    this.consecutiveSuccessfulLaunches = consecutiveSuccessfulLaunches;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSuccessfulLaunches() {
    return successfulLaunches;
  }
  public void setSuccessfulLaunches(String successfulLaunches) {
    this.successfulLaunches = successfulLaunches;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFailedLaunches() {
    return failedLaunches;
  }
  public void setFailedLaunches(String failedLaunches) {
    this.failedLaunches = failedLaunches;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPendingLaunches() {
    return pendingLaunches;
  }
  public void setPendingLaunches(String pendingLaunches) {
    this.pendingLaunches = pendingLaunches;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LauncherConfigDetail launcherConfigDetail = (LauncherConfigDetail) o;
    return (this.id == null ? launcherConfigDetail.id == null : this.id.equals(launcherConfigDetail.id)) &&
        (this.launchLibraryId == null ? launcherConfigDetail.launchLibraryId == null : this.launchLibraryId.equals(launcherConfigDetail.launchLibraryId)) &&
        (this.url == null ? launcherConfigDetail.url == null : this.url.equals(launcherConfigDetail.url)) &&
        (this.name == null ? launcherConfigDetail.name == null : this.name.equals(launcherConfigDetail.name)) &&
        (this.description == null ? launcherConfigDetail.description == null : this.description.equals(launcherConfigDetail.description)) &&
        (this.family == null ? launcherConfigDetail.family == null : this.family.equals(launcherConfigDetail.family)) &&
        (this.fullName == null ? launcherConfigDetail.fullName == null : this.fullName.equals(launcherConfigDetail.fullName)) &&
        (this.manufacturer == null ? launcherConfigDetail.manufacturer == null : this.manufacturer.equals(launcherConfigDetail.manufacturer)) &&
        (this.program == null ? launcherConfigDetail.program == null : this.program.equals(launcherConfigDetail.program)) &&
        (this.variant == null ? launcherConfigDetail.variant == null : this.variant.equals(launcherConfigDetail.variant)) &&
        (this.alias == null ? launcherConfigDetail.alias == null : this.alias.equals(launcherConfigDetail.alias)) &&
        (this.minStage == null ? launcherConfigDetail.minStage == null : this.minStage.equals(launcherConfigDetail.minStage)) &&
        (this.maxStage == null ? launcherConfigDetail.maxStage == null : this.maxStage.equals(launcherConfigDetail.maxStage)) &&
        (this.length == null ? launcherConfigDetail.length == null : this.length.equals(launcherConfigDetail.length)) &&
        (this.diameter == null ? launcherConfigDetail.diameter == null : this.diameter.equals(launcherConfigDetail.diameter)) &&
        (this.maidenFlight == null ? launcherConfigDetail.maidenFlight == null : this.maidenFlight.equals(launcherConfigDetail.maidenFlight)) &&
        (this.launchMass == null ? launcherConfigDetail.launchMass == null : this.launchMass.equals(launcherConfigDetail.launchMass)) &&
        (this.leoCapacity == null ? launcherConfigDetail.leoCapacity == null : this.leoCapacity.equals(launcherConfigDetail.leoCapacity)) &&
        (this.gtoCapacity == null ? launcherConfigDetail.gtoCapacity == null : this.gtoCapacity.equals(launcherConfigDetail.gtoCapacity)) &&
        (this.toThrust == null ? launcherConfigDetail.toThrust == null : this.toThrust.equals(launcherConfigDetail.toThrust)) &&
        (this.apogee == null ? launcherConfigDetail.apogee == null : this.apogee.equals(launcherConfigDetail.apogee)) &&
        (this.vehicleRange == null ? launcherConfigDetail.vehicleRange == null : this.vehicleRange.equals(launcherConfigDetail.vehicleRange)) &&
        (this.imageUrl == null ? launcherConfigDetail.imageUrl == null : this.imageUrl.equals(launcherConfigDetail.imageUrl)) &&
        (this.infoUrl == null ? launcherConfigDetail.infoUrl == null : this.infoUrl.equals(launcherConfigDetail.infoUrl)) &&
        (this.wikiUrl == null ? launcherConfigDetail.wikiUrl == null : this.wikiUrl.equals(launcherConfigDetail.wikiUrl)) &&
        (this.totalLaunchCount == null ? launcherConfigDetail.totalLaunchCount == null : this.totalLaunchCount.equals(launcherConfigDetail.totalLaunchCount)) &&
        (this.consecutiveSuccessfulLaunches == null ? launcherConfigDetail.consecutiveSuccessfulLaunches == null : this.consecutiveSuccessfulLaunches.equals(launcherConfigDetail.consecutiveSuccessfulLaunches)) &&
        (this.successfulLaunches == null ? launcherConfigDetail.successfulLaunches == null : this.successfulLaunches.equals(launcherConfigDetail.successfulLaunches)) &&
        (this.failedLaunches == null ? launcherConfigDetail.failedLaunches == null : this.failedLaunches.equals(launcherConfigDetail.failedLaunches)) &&
        (this.pendingLaunches == null ? launcherConfigDetail.pendingLaunches == null : this.pendingLaunches.equals(launcherConfigDetail.pendingLaunches));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.launchLibraryId == null ? 0: this.launchLibraryId.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.family == null ? 0: this.family.hashCode());
    result = 31 * result + (this.fullName == null ? 0: this.fullName.hashCode());
    result = 31 * result + (this.manufacturer == null ? 0: this.manufacturer.hashCode());
    result = 31 * result + (this.program == null ? 0: this.program.hashCode());
    result = 31 * result + (this.variant == null ? 0: this.variant.hashCode());
    result = 31 * result + (this.alias == null ? 0: this.alias.hashCode());
    result = 31 * result + (this.minStage == null ? 0: this.minStage.hashCode());
    result = 31 * result + (this.maxStage == null ? 0: this.maxStage.hashCode());
    result = 31 * result + (this.length == null ? 0: this.length.hashCode());
    result = 31 * result + (this.diameter == null ? 0: this.diameter.hashCode());
    result = 31 * result + (this.maidenFlight == null ? 0: this.maidenFlight.hashCode());
    result = 31 * result + (this.launchMass == null ? 0: this.launchMass.hashCode());
    result = 31 * result + (this.leoCapacity == null ? 0: this.leoCapacity.hashCode());
    result = 31 * result + (this.gtoCapacity == null ? 0: this.gtoCapacity.hashCode());
    result = 31 * result + (this.toThrust == null ? 0: this.toThrust.hashCode());
    result = 31 * result + (this.apogee == null ? 0: this.apogee.hashCode());
    result = 31 * result + (this.vehicleRange == null ? 0: this.vehicleRange.hashCode());
    result = 31 * result + (this.imageUrl == null ? 0: this.imageUrl.hashCode());
    result = 31 * result + (this.infoUrl == null ? 0: this.infoUrl.hashCode());
    result = 31 * result + (this.wikiUrl == null ? 0: this.wikiUrl.hashCode());
    result = 31 * result + (this.totalLaunchCount == null ? 0: this.totalLaunchCount.hashCode());
    result = 31 * result + (this.consecutiveSuccessfulLaunches == null ? 0: this.consecutiveSuccessfulLaunches.hashCode());
    result = 31 * result + (this.successfulLaunches == null ? 0: this.successfulLaunches.hashCode());
    result = 31 * result + (this.failedLaunches == null ? 0: this.failedLaunches.hashCode());
    result = 31 * result + (this.pendingLaunches == null ? 0: this.pendingLaunches.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LauncherConfigDetail {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  launchLibraryId: ").append(launchLibraryId).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  family: ").append(family).append("\n");
    sb.append("  fullName: ").append(fullName).append("\n");
    sb.append("  manufacturer: ").append(manufacturer).append("\n");
    sb.append("  program: ").append(program).append("\n");
    sb.append("  variant: ").append(variant).append("\n");
    sb.append("  alias: ").append(alias).append("\n");
    sb.append("  minStage: ").append(minStage).append("\n");
    sb.append("  maxStage: ").append(maxStage).append("\n");
    sb.append("  length: ").append(length).append("\n");
    sb.append("  diameter: ").append(diameter).append("\n");
    sb.append("  maidenFlight: ").append(maidenFlight).append("\n");
    sb.append("  launchMass: ").append(launchMass).append("\n");
    sb.append("  leoCapacity: ").append(leoCapacity).append("\n");
    sb.append("  gtoCapacity: ").append(gtoCapacity).append("\n");
    sb.append("  toThrust: ").append(toThrust).append("\n");
    sb.append("  apogee: ").append(apogee).append("\n");
    sb.append("  vehicleRange: ").append(vehicleRange).append("\n");
    sb.append("  imageUrl: ").append(imageUrl).append("\n");
    sb.append("  infoUrl: ").append(infoUrl).append("\n");
    sb.append("  wikiUrl: ").append(wikiUrl).append("\n");
    sb.append("  totalLaunchCount: ").append(totalLaunchCount).append("\n");
    sb.append("  consecutiveSuccessfulLaunches: ").append(consecutiveSuccessfulLaunches).append("\n");
    sb.append("  successfulLaunches: ").append(successfulLaunches).append("\n");
    sb.append("  failedLaunches: ").append(failedLaunches).append("\n");
    sb.append("  pendingLaunches: ").append(pendingLaunches).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
