/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.AstronautFlight;
import io.swagger.client.model.DockingEventSerializerForSpacecraftFlight;
import io.swagger.client.model.LaunchSerializerCommon;
import io.swagger.client.model.SpacecraftDetailedNoFlights;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SpacecraftFlightDetailed {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("mission_end")
  private Date missionEnd = null;
  @SerializedName("destination")
  private String destination = null;
  @SerializedName("launch_crew")
  private List<AstronautFlight> launchCrew = null;
  @SerializedName("onboard_crew")
  private List<AstronautFlight> onboardCrew = null;
  @SerializedName("landing_crew")
  private List<AstronautFlight> landingCrew = null;
  @SerializedName("spacecraft")
  private SpacecraftDetailedNoFlights spacecraft = null;
  @SerializedName("launch")
  private LaunchSerializerCommon launch = null;
  @SerializedName("docking_events")
  private List<DockingEventSerializerForSpacecraftFlight> dockingEvents = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getMissionEnd() {
    return missionEnd;
  }
  public void setMissionEnd(Date missionEnd) {
    this.missionEnd = missionEnd;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDestination() {
    return destination;
  }
  public void setDestination(String destination) {
    this.destination = destination;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<AstronautFlight> getLaunchCrew() {
    return launchCrew;
  }
  public void setLaunchCrew(List<AstronautFlight> launchCrew) {
    this.launchCrew = launchCrew;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<AstronautFlight> getOnboardCrew() {
    return onboardCrew;
  }
  public void setOnboardCrew(List<AstronautFlight> onboardCrew) {
    this.onboardCrew = onboardCrew;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<AstronautFlight> getLandingCrew() {
    return landingCrew;
  }
  public void setLandingCrew(List<AstronautFlight> landingCrew) {
    this.landingCrew = landingCrew;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SpacecraftDetailedNoFlights getSpacecraft() {
    return spacecraft;
  }
  public void setSpacecraft(SpacecraftDetailedNoFlights spacecraft) {
    this.spacecraft = spacecraft;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public LaunchSerializerCommon getLaunch() {
    return launch;
  }
  public void setLaunch(LaunchSerializerCommon launch) {
    this.launch = launch;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<DockingEventSerializerForSpacecraftFlight> getDockingEvents() {
    return dockingEvents;
  }
  public void setDockingEvents(List<DockingEventSerializerForSpacecraftFlight> dockingEvents) {
    this.dockingEvents = dockingEvents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpacecraftFlightDetailed spacecraftFlightDetailed = (SpacecraftFlightDetailed) o;
    return (this.id == null ? spacecraftFlightDetailed.id == null : this.id.equals(spacecraftFlightDetailed.id)) &&
        (this.url == null ? spacecraftFlightDetailed.url == null : this.url.equals(spacecraftFlightDetailed.url)) &&
        (this.missionEnd == null ? spacecraftFlightDetailed.missionEnd == null : this.missionEnd.equals(spacecraftFlightDetailed.missionEnd)) &&
        (this.destination == null ? spacecraftFlightDetailed.destination == null : this.destination.equals(spacecraftFlightDetailed.destination)) &&
        (this.launchCrew == null ? spacecraftFlightDetailed.launchCrew == null : this.launchCrew.equals(spacecraftFlightDetailed.launchCrew)) &&
        (this.onboardCrew == null ? spacecraftFlightDetailed.onboardCrew == null : this.onboardCrew.equals(spacecraftFlightDetailed.onboardCrew)) &&
        (this.landingCrew == null ? spacecraftFlightDetailed.landingCrew == null : this.landingCrew.equals(spacecraftFlightDetailed.landingCrew)) &&
        (this.spacecraft == null ? spacecraftFlightDetailed.spacecraft == null : this.spacecraft.equals(spacecraftFlightDetailed.spacecraft)) &&
        (this.launch == null ? spacecraftFlightDetailed.launch == null : this.launch.equals(spacecraftFlightDetailed.launch)) &&
        (this.dockingEvents == null ? spacecraftFlightDetailed.dockingEvents == null : this.dockingEvents.equals(spacecraftFlightDetailed.dockingEvents));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.missionEnd == null ? 0: this.missionEnd.hashCode());
    result = 31 * result + (this.destination == null ? 0: this.destination.hashCode());
    result = 31 * result + (this.launchCrew == null ? 0: this.launchCrew.hashCode());
    result = 31 * result + (this.onboardCrew == null ? 0: this.onboardCrew.hashCode());
    result = 31 * result + (this.landingCrew == null ? 0: this.landingCrew.hashCode());
    result = 31 * result + (this.spacecraft == null ? 0: this.spacecraft.hashCode());
    result = 31 * result + (this.launch == null ? 0: this.launch.hashCode());
    result = 31 * result + (this.dockingEvents == null ? 0: this.dockingEvents.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpacecraftFlightDetailed {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  missionEnd: ").append(missionEnd).append("\n");
    sb.append("  destination: ").append(destination).append("\n");
    sb.append("  launchCrew: ").append(launchCrew).append("\n");
    sb.append("  onboardCrew: ").append(onboardCrew).append("\n");
    sb.append("  landingCrew: ").append(landingCrew).append("\n");
    sb.append("  spacecraft: ").append(spacecraft).append("\n");
    sb.append("  launch: ").append(launch).append("\n");
    sb.append("  dockingEvents: ").append(dockingEvents).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
