/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package apimodels;

import com.google.gson.annotations.SerializedName;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class DockingEventDetailed {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("launch_id")
  private String launchId = null;
  @SerializedName("docking")
  private Date docking = null;
  @SerializedName("departure")
  private Date departure = null;
  @SerializedName("flight_vehicle")
  private SpacecraftFlightSerializerForDockingEventDetailed flightVehicle = null;
  @SerializedName("docking_location")
  private DockingLocation dockingLocation = null;
  @SerializedName("space_station")
  private SpaceStationSerializerForDockingEvent spaceStation = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getLaunchId() {
    return launchId;
  }
  public void setLaunchId(String launchId) {
    this.launchId = launchId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getDocking() {
    return docking;
  }
  public void setDocking(Date docking) {
    this.docking = docking;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDeparture() {
    return departure;
  }
  public void setDeparture(Date departure) {
    this.departure = departure;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SpacecraftFlightSerializerForDockingEventDetailed getFlightVehicle() {
    return flightVehicle;
  }
  public void setFlightVehicle(SpacecraftFlightSerializerForDockingEventDetailed flightVehicle) {
    this.flightVehicle = flightVehicle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DockingLocation getDockingLocation() {
    return dockingLocation;
  }
  public void setDockingLocation(DockingLocation dockingLocation) {
    this.dockingLocation = dockingLocation;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SpaceStationSerializerForDockingEvent getSpaceStation() {
    return spaceStation;
  }
  public void setSpaceStation(SpaceStationSerializerForDockingEvent spaceStation) {
    this.spaceStation = spaceStation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DockingEventDetailed dockingEventDetailed = (DockingEventDetailed) o;
    return (this.id == null ? dockingEventDetailed.id == null : this.id.equals(dockingEventDetailed.id)) &&
        (this.url == null ? dockingEventDetailed.url == null : this.url.equals(dockingEventDetailed.url)) &&
        (this.launchId == null ? dockingEventDetailed.launchId == null : this.launchId.equals(dockingEventDetailed.launchId)) &&
        (this.docking == null ? dockingEventDetailed.docking == null : this.docking.equals(dockingEventDetailed.docking)) &&
        (this.departure == null ? dockingEventDetailed.departure == null : this.departure.equals(dockingEventDetailed.departure)) &&
        (this.flightVehicle == null ? dockingEventDetailed.flightVehicle == null : this.flightVehicle.equals(dockingEventDetailed.flightVehicle)) &&
        (this.dockingLocation == null ? dockingEventDetailed.dockingLocation == null : this.dockingLocation.equals(dockingEventDetailed.dockingLocation)) &&
        (this.spaceStation == null ? dockingEventDetailed.spaceStation == null : this.spaceStation.equals(dockingEventDetailed.spaceStation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.launchId == null ? 0: this.launchId.hashCode());
    result = 31 * result + (this.docking == null ? 0: this.docking.hashCode());
    result = 31 * result + (this.departure == null ? 0: this.departure.hashCode());
    result = 31 * result + (this.flightVehicle == null ? 0: this.flightVehicle.hashCode());
    result = 31 * result + (this.dockingLocation == null ? 0: this.dockingLocation.hashCode());
    result = 31 * result + (this.spaceStation == null ? 0: this.spaceStation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DockingEventDetailed {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  launchId: ").append(launchId).append("\n");
    sb.append("  docking: ").append(docking).append("\n");
    sb.append("  departure: ").append(departure).append("\n");
    sb.append("  flightVehicle: ").append(flightVehicle).append("\n");
    sb.append("  dockingLocation: ").append(dockingLocation).append("\n");
    sb.append("  spaceStation: ").append(spaceStation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
