/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package apimodels;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class Mission {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("launch_library_id")
  private Integer launchLibraryId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("launch_designator")
  private String launchDesignator = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("orbit")
  private Orbit orbit = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * minimum: -2147483648
   * maximum: 2147483647
   **/
  @ApiModelProperty(value = "")
  public Integer getLaunchLibraryId() {
    return launchLibraryId;
  }
  public void setLaunchLibraryId(Integer launchLibraryId) {
    this.launchLibraryId = launchLibraryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLaunchDesignator() {
    return launchDesignator;
  }
  public void setLaunchDesignator(String launchDesignator) {
    this.launchDesignator = launchDesignator;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Orbit getOrbit() {
    return orbit;
  }
  public void setOrbit(Orbit orbit) {
    this.orbit = orbit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mission mission = (Mission) o;
    return (this.id == null ? mission.id == null : this.id.equals(mission.id)) &&
        (this.launchLibraryId == null ? mission.launchLibraryId == null : this.launchLibraryId.equals(mission.launchLibraryId)) &&
        (this.name == null ? mission.name == null : this.name.equals(mission.name)) &&
        (this.description == null ? mission.description == null : this.description.equals(mission.description)) &&
        (this.launchDesignator == null ? mission.launchDesignator == null : this.launchDesignator.equals(mission.launchDesignator)) &&
        (this.type == null ? mission.type == null : this.type.equals(mission.type)) &&
        (this.orbit == null ? mission.orbit == null : this.orbit.equals(mission.orbit));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.launchLibraryId == null ? 0: this.launchLibraryId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.launchDesignator == null ? 0: this.launchDesignator.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.orbit == null ? 0: this.orbit.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mission {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  launchLibraryId: ").append(launchLibraryId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  launchDesignator: ").append(launchDesignator).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  orbit: ").append(orbit).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
