/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ll2.models;

import com.google.gson.annotations.SerializedName;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class AstronautDetailedSerializerNoFlights {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("type")
  private AstronautType type = null;
  @SerializedName("status")
  private AstronautStatus status = null;
  @SerializedName("agency")
  private AgencySerializerMini agency = null;
  @SerializedName("date_of_birth")
  private Date dateOfBirth = null;
  @SerializedName("date_of_death")
  private Date dateOfDeath = null;
  @SerializedName("nationality")
  private String nationality = null;
  @SerializedName("twitter")
  private String twitter = null;
  @SerializedName("instagram")
  private String instagram = null;
  @SerializedName("bio")
  private String bio = null;
  @SerializedName("profile_image")
  private String profileImage = null;
  @SerializedName("wiki")
  private String wiki = null;
  @SerializedName("last_flight")
  private String lastFlight = null;
  @SerializedName("first_flight")
  private String firstFlight = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public AstronautType getType() {
    return type;
  }
  public void setType(AstronautType type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public AstronautStatus getStatus() {
    return status;
  }
  public void setStatus(AstronautStatus status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public AgencySerializerMini getAgency() {
    return agency;
  }
  public void setAgency(AgencySerializerMini agency) {
    this.agency = agency;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getDateOfBirth() {
    return dateOfBirth;
  }
  public void setDateOfBirth(Date dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDateOfDeath() {
    return dateOfDeath;
  }
  public void setDateOfDeath(Date dateOfDeath) {
    this.dateOfDeath = dateOfDeath;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getNationality() {
    return nationality;
  }
  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTwitter() {
    return twitter;
  }
  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInstagram() {
    return instagram;
  }
  public void setInstagram(String instagram) {
    this.instagram = instagram;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getBio() {
    return bio;
  }
  public void setBio(String bio) {
    this.bio = bio;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProfileImage() {
    return profileImage;
  }
  public void setProfileImage(String profileImage) {
    this.profileImage = profileImage;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWiki() {
    return wiki;
  }
  public void setWiki(String wiki) {
    this.wiki = wiki;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastFlight() {
    return lastFlight;
  }
  public void setLastFlight(String lastFlight) {
    this.lastFlight = lastFlight;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstFlight() {
    return firstFlight;
  }
  public void setFirstFlight(String firstFlight) {
    this.firstFlight = firstFlight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AstronautDetailedSerializerNoFlights astronautDetailedSerializerNoFlights = (AstronautDetailedSerializerNoFlights) o;
    return (this.id == null ? astronautDetailedSerializerNoFlights.id == null : this.id.equals(astronautDetailedSerializerNoFlights.id)) &&
        (this.url == null ? astronautDetailedSerializerNoFlights.url == null : this.url.equals(astronautDetailedSerializerNoFlights.url)) &&
        (this.name == null ? astronautDetailedSerializerNoFlights.name == null : this.name.equals(astronautDetailedSerializerNoFlights.name)) &&
        (this.type == null ? astronautDetailedSerializerNoFlights.type == null : this.type.equals(astronautDetailedSerializerNoFlights.type)) &&
        (this.status == null ? astronautDetailedSerializerNoFlights.status == null : this.status.equals(astronautDetailedSerializerNoFlights.status)) &&
        (this.agency == null ? astronautDetailedSerializerNoFlights.agency == null : this.agency.equals(astronautDetailedSerializerNoFlights.agency)) &&
        (this.dateOfBirth == null ? astronautDetailedSerializerNoFlights.dateOfBirth == null : this.dateOfBirth.equals(astronautDetailedSerializerNoFlights.dateOfBirth)) &&
        (this.dateOfDeath == null ? astronautDetailedSerializerNoFlights.dateOfDeath == null : this.dateOfDeath.equals(astronautDetailedSerializerNoFlights.dateOfDeath)) &&
        (this.nationality == null ? astronautDetailedSerializerNoFlights.nationality == null : this.nationality.equals(astronautDetailedSerializerNoFlights.nationality)) &&
        (this.twitter == null ? astronautDetailedSerializerNoFlights.twitter == null : this.twitter.equals(astronautDetailedSerializerNoFlights.twitter)) &&
        (this.instagram == null ? astronautDetailedSerializerNoFlights.instagram == null : this.instagram.equals(astronautDetailedSerializerNoFlights.instagram)) &&
        (this.bio == null ? astronautDetailedSerializerNoFlights.bio == null : this.bio.equals(astronautDetailedSerializerNoFlights.bio)) &&
        (this.profileImage == null ? astronautDetailedSerializerNoFlights.profileImage == null : this.profileImage.equals(astronautDetailedSerializerNoFlights.profileImage)) &&
        (this.wiki == null ? astronautDetailedSerializerNoFlights.wiki == null : this.wiki.equals(astronautDetailedSerializerNoFlights.wiki)) &&
        (this.lastFlight == null ? astronautDetailedSerializerNoFlights.lastFlight == null : this.lastFlight.equals(astronautDetailedSerializerNoFlights.lastFlight)) &&
        (this.firstFlight == null ? astronautDetailedSerializerNoFlights.firstFlight == null : this.firstFlight.equals(astronautDetailedSerializerNoFlights.firstFlight));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.agency == null ? 0: this.agency.hashCode());
    result = 31 * result + (this.dateOfBirth == null ? 0: this.dateOfBirth.hashCode());
    result = 31 * result + (this.dateOfDeath == null ? 0: this.dateOfDeath.hashCode());
    result = 31 * result + (this.nationality == null ? 0: this.nationality.hashCode());
    result = 31 * result + (this.twitter == null ? 0: this.twitter.hashCode());
    result = 31 * result + (this.instagram == null ? 0: this.instagram.hashCode());
    result = 31 * result + (this.bio == null ? 0: this.bio.hashCode());
    result = 31 * result + (this.profileImage == null ? 0: this.profileImage.hashCode());
    result = 31 * result + (this.wiki == null ? 0: this.wiki.hashCode());
    result = 31 * result + (this.lastFlight == null ? 0: this.lastFlight.hashCode());
    result = 31 * result + (this.firstFlight == null ? 0: this.firstFlight.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AstronautDetailedSerializerNoFlights {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  agency: ").append(agency).append("\n");
    sb.append("  dateOfBirth: ").append(dateOfBirth).append("\n");
    sb.append("  dateOfDeath: ").append(dateOfDeath).append("\n");
    sb.append("  nationality: ").append(nationality).append("\n");
    sb.append("  twitter: ").append(twitter).append("\n");
    sb.append("  instagram: ").append(instagram).append("\n");
    sb.append("  bio: ").append(bio).append("\n");
    sb.append("  profileImage: ").append(profileImage).append("\n");
    sb.append("  wiki: ").append(wiki).append("\n");
    sb.append("  lastFlight: ").append(lastFlight).append("\n");
    sb.append("  firstFlight: ").append(firstFlight).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
