/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ll2.models;

import com.google.gson.annotations.SerializedName;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class DockingEventDetailedSerializerForSpacestation {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("docking")
  private Date docking = null;
  @SerializedName("departure")
  private Date departure = null;
  @SerializedName("flight_vehicle")
  private SpacecraftFlightForDockingEvent flightVehicle = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getDocking() {
    return docking;
  }
  public void setDocking(Date docking) {
    this.docking = docking;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDeparture() {
    return departure;
  }
  public void setDeparture(Date departure) {
    this.departure = departure;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SpacecraftFlightForDockingEvent getFlightVehicle() {
    return flightVehicle;
  }
  public void setFlightVehicle(SpacecraftFlightForDockingEvent flightVehicle) {
    this.flightVehicle = flightVehicle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DockingEventDetailedSerializerForSpacestation dockingEventDetailedSerializerForSpacestation = (DockingEventDetailedSerializerForSpacestation) o;
    return (this.id == null ? dockingEventDetailedSerializerForSpacestation.id == null : this.id.equals(dockingEventDetailedSerializerForSpacestation.id)) &&
        (this.url == null ? dockingEventDetailedSerializerForSpacestation.url == null : this.url.equals(dockingEventDetailedSerializerForSpacestation.url)) &&
        (this.docking == null ? dockingEventDetailedSerializerForSpacestation.docking == null : this.docking.equals(dockingEventDetailedSerializerForSpacestation.docking)) &&
        (this.departure == null ? dockingEventDetailedSerializerForSpacestation.departure == null : this.departure.equals(dockingEventDetailedSerializerForSpacestation.departure)) &&
        (this.flightVehicle == null ? dockingEventDetailedSerializerForSpacestation.flightVehicle == null : this.flightVehicle.equals(dockingEventDetailedSerializerForSpacestation.flightVehicle));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.docking == null ? 0: this.docking.hashCode());
    result = 31 * result + (this.departure == null ? 0: this.departure.hashCode());
    result = 31 * result + (this.flightVehicle == null ? 0: this.flightVehicle.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DockingEventDetailedSerializerForSpacestation {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  docking: ").append(docking).append("\n");
    sb.append("  departure: ").append(departure).append("\n");
    sb.append("  flightVehicle: ").append(flightVehicle).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
