/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ll2.models;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class Spacecraft {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("serial_number")
  private String serialNumber = null;
  @SerializedName("status")
  private SpacecraftStatus status = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("spacecraft_config")
  private SpacecraftConfig spacecraftConfig = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSerialNumber() {
    return serialNumber;
  }
  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SpacecraftStatus getStatus() {
    return status;
  }
  public void setStatus(SpacecraftStatus status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SpacecraftConfig getSpacecraftConfig() {
    return spacecraftConfig;
  }
  public void setSpacecraftConfig(SpacecraftConfig spacecraftConfig) {
    this.spacecraftConfig = spacecraftConfig;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Spacecraft spacecraft = (Spacecraft) o;
    return (this.id == null ? spacecraft.id == null : this.id.equals(spacecraft.id)) &&
        (this.url == null ? spacecraft.url == null : this.url.equals(spacecraft.url)) &&
        (this.name == null ? spacecraft.name == null : this.name.equals(spacecraft.name)) &&
        (this.serialNumber == null ? spacecraft.serialNumber == null : this.serialNumber.equals(spacecraft.serialNumber)) &&
        (this.status == null ? spacecraft.status == null : this.status.equals(spacecraft.status)) &&
        (this.description == null ? spacecraft.description == null : this.description.equals(spacecraft.description)) &&
        (this.spacecraftConfig == null ? spacecraft.spacecraftConfig == null : this.spacecraftConfig.equals(spacecraft.spacecraftConfig));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.serialNumber == null ? 0: this.serialNumber.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.spacecraftConfig == null ? 0: this.spacecraftConfig.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Spacecraft {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  serialNumber: ").append(serialNumber).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  spacecraftConfig: ").append(spacecraftConfig).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
