/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.
 *
 * OpenAPI spec version: v2.0.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiInvoker;
import io.swagger.client.ApiException;
import io.swagger.client.Pair;

import io.swagger.client.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import io.swagger.client.model.ExpeditionDetail;
import io.swagger.client.model.InlineResponse2006;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class ExpeditionApi {
  String basePath = "https://ll.thespacedevs.com/2.0.0";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
  * 
  * API endpoint that allows Expeditions to be viewed.
   * @param crewAstronautAgency 
   * @param spaceStation 
   * @param crewAstronaut 
   * @param name 
   * @param startGt 
   * @param startLt 
   * @param startGte 
   * @param startLte 
   * @param endGt 
   * @param endLt 
   * @param endGte 
   * @param endLte 
   * @param search A search term.
   * @param ordering Which field to use when ordering the results.
   * @param limit Number of results to return per page.
   * @param offset The initial index from which to return the results.
   * @return InlineResponse2006
  */
  public InlineResponse2006 expeditionList (String crewAstronautAgency, String spaceStation, String crewAstronaut, String name, String startGt, String startLt, String startGte, String startLte, String endGt, String endLt, String endGte, String endLte, String search, String ordering, Integer limit, Integer offset) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;

    // create path and map variables
    String path = "/expedition/";

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    queryParams.addAll(ApiInvoker.parameterToPairs("", "crew__astronaut__agency", crewAstronautAgency));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "space_station", spaceStation));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "crew__astronaut", crewAstronaut));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "name", name));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start__gt", startGt));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start__lt", startLt));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start__gte", startGte));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start__lte", startLte));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end__gt", endGt));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end__lt", endLt));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end__gte", endGte));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end__lte", endLte));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "search", search));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "ordering", ordering));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "limit", limit));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "offset", offset));
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "Token" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (InlineResponse2006) ApiInvoker.deserialize(localVarResponse, "", InlineResponse2006.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * 
   * API endpoint that allows Expeditions to be viewed.
   * @param crewAstronautAgency    * @param spaceStation    * @param crewAstronaut    * @param name    * @param startGt    * @param startLt    * @param startGte    * @param startLte    * @param endGt    * @param endLt    * @param endGte    * @param endLte    * @param search A search term.   * @param ordering Which field to use when ordering the results.   * @param limit Number of results to return per page.   * @param offset The initial index from which to return the results.
  */
  public void expeditionList (String crewAstronautAgency, String spaceStation, String crewAstronaut, String name, String startGt, String startLt, String startGte, String startLte, String endGt, String endLt, String endGte, String endLte, String search, String ordering, Integer limit, Integer offset, final Response.Listener<InlineResponse2006> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;


    // create path and map variables
    String path = "/expedition/".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();

    queryParams.addAll(ApiInvoker.parameterToPairs("", "crew__astronaut__agency", crewAstronautAgency));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "space_station", spaceStation));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "crew__astronaut", crewAstronaut));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "name", name));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start__gt", startGt));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start__lt", startLt));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start__gte", startGte));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start__lte", startLte));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end__gt", endGt));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end__lt", endLt));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end__gte", endGte));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end__lte", endLte));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "search", search));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "ordering", ordering));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "limit", limit));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "offset", offset));


    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "Token" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((InlineResponse2006) ApiInvoker.deserialize(localVarResponse,  "", InlineResponse2006.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * 
  * API endpoint that allows Expeditions to be viewed.
   * @param id A unique integer value identifying this expedition.
   * @return ExpeditionDetail
  */
  public ExpeditionDetail expeditionRead (Integer id) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'id' is set
    if (id == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'id' when calling expeditionRead",
        new ApiException(400, "Missing the required parameter 'id' when calling expeditionRead"));
    }

    // create path and map variables
    String path = "/expedition/{id}/".replaceAll("\\{" + "id" + "\\}", apiInvoker.escapeString(id.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "Token" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ExpeditionDetail) ApiInvoker.deserialize(localVarResponse, "", ExpeditionDetail.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * 
   * API endpoint that allows Expeditions to be viewed.
   * @param id A unique integer value identifying this expedition.
  */
  public void expeditionRead (Integer id, final Response.Listener<ExpeditionDetail> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'id' is set
    if (id == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'id' when calling expeditionRead",
        new ApiException(400, "Missing the required parameter 'id' when calling expeditionRead"));
    }

    // create path and map variables
    String path = "/expedition/{id}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "id" + "\\}", apiInvoker.escapeString(id.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "Token" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ExpeditionDetail) ApiInvoker.deserialize(localVarResponse,  "", ExpeditionDetail.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
}
